-- MySQL Script generated by MySQL Workbench
-- Wed Apr 25 13:54:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema internship_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema internship_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `internship_web` DEFAULT CHARACTER SET utf8mb4 ;
USE `internship_web` ;

-- -----------------------------------------------------
-- Table `internship_web`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`account` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  `nickname` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  `salt` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  `type` VARCHAR(8) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL DEFAULT 'student',
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`student` (
  `account_userID` INT NOT NULL,
  `name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `class` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `grade` INT(2) NULL,
  `majors` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `address` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `dateOfBirth` DATE NULL,
  `vnumail` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `cpa` INT(2) NULL,
  `graduationYear` YEAR(4) NULL,
  `picture` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  `email` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  `skypeID` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  `facebook` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  `position` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  `favorite` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  `orientation` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  `note` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`account_userID`),
  INDEX `fk_student_account1_idx` (`account_userID` ASC),
  CONSTRAINT `fk_student_account1`
    FOREIGN KEY (`account_userID`)
    REFERENCES `internship_web`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`partner` (
  `account_userID` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `logo` VARCHAR(100) NULL,
  PRIMARY KEY (`account_userID`),
  INDEX `fk_partner_account1_idx` (`account_userID` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_partner_account1`
    FOREIGN KEY (`account_userID`)
    REFERENCES `internship_web`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`term`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`term` (
  `termID` INT NOT NULL AUTO_INCREMENT,
  `start` DATE NOT NULL,
  `end` DATE NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`termID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_web`.`internship_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`internship_job` (
  `jobID` INT NOT NULL AUTO_INCREMENT,
  `partner_account_userID` INT NOT NULL,
  `term_termID` INT NOT NULL,
  PRIMARY KEY (`jobID`),
  INDEX `fk_internship_job_partner1_idx` (`partner_account_userID` ASC),
  INDEX `fk_internship_job_term1_idx` (`term_termID` ASC),
  UNIQUE INDEX `jobID_UNIQUE` (`jobID` ASC),
  CONSTRAINT `fk_internship_job_partner1`
    FOREIGN KEY (`partner_account_userID`)
    REFERENCES `internship_web`.`partner` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_internship_job_term1`
    FOREIGN KEY (`term_termID`)
    REFERENCES `internship_web`.`term` (`termID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`file` (
  `fileID` BIGINT(6) NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(100) NOT NULL,
  `fileType` VARCHAR(5) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  `path` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  PRIMARY KEY (`fileID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`plan_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`plan_report` (
  ` plan_reportID` INT NOT NULL AUTO_INCREMENT,
  `studentID` INT NOT NULL,
  `jobID` INT NOT NULL,
  `file_fileID` BIGINT(6) NOT NULL,
  `title` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `content` VARCHAR(1000) NULL,
  `isFinal` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (` plan_reportID`),
  INDEX `fk_ planreport_student1_idx` (`studentID` ASC),
  INDEX `fk_ planreport_internship_job1_idx` (`jobID` ASC),
  INDEX `fk_ planreport_file1_idx` (`file_fileID` ASC),
  UNIQUE INDEX ` plan_reportID_UNIQUE` (` plan_reportID` ASC),
  CONSTRAINT `fk_ planreport_student1`
    FOREIGN KEY (`studentID`)
    REFERENCES `internship_web`.`student` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ planreport_internship_job1`
    FOREIGN KEY (`jobID`)
    REFERENCES `internship_web`.`internship_job` (`jobID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ planreport_file1`
    FOREIGN KEY (`file_fileID`)
    REFERENCES `internship_web`.`file` (`fileID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`admin` (
  `account_userID` INT NOT NULL,
  `name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `vnumail` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `phoneNumber` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `email` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  PRIMARY KEY (`account_userID`),
  INDEX `fk_admin_account1_idx` (`account_userID` ASC),
  CONSTRAINT `fk_admin_account1`
    FOREIGN KEY (`account_userID`)
    REFERENCES `internship_web`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`comment` (
  `commentID` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  `account_userID` INT NOT NULL,
  ` plan_report_ plan_reportID` INT NOT NULL,
  PRIMARY KEY (`commentID`),
  INDEX `fk_comment_account1_idx` (`account_userID` ASC),
  INDEX `fk_comment_ plan_report1_idx` (` plan_report_ plan_reportID` ASC),
  CONSTRAINT `fk_comment_account1`
    FOREIGN KEY (`account_userID`)
    REFERENCES `internship_web`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_ plan_report1`
    FOREIGN KEY (` plan_report_ plan_reportID`)
    REFERENCES `internship_web`.`plan_report` (` plan_reportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`lecturer` (
  `account_userID` INT NOT NULL,
  `name` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `vnumail` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `gmail` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `phoneNumber` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL,
  `note` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`account_userID`),
  INDEX `fk_lecturer_account1_idx` (`account_userID` ASC),
  CONSTRAINT `fk_lecturer_account1`
    FOREIGN KEY (`account_userID`)
    REFERENCES `internship_web`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`message` (
  `senderID` INT NOT NULL,
  `receiverID` INT NOT NULL,
  `title` VARCHAR(200) NULL,
  `content` VARCHAR(1000) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  PRIMARY KEY (`senderID`, `receiverID`),
  INDEX `message_fk1` (`receiverID` ASC),
  CONSTRAINT `message_fk0`
    FOREIGN KEY (`senderID`)
    REFERENCES `internship_web`.`account` (`userID`),
  CONSTRAINT `message_fk1`
    FOREIGN KEY (`receiverID`)
    REFERENCES `internship_web`.`account` (`userID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`skill` (
  `skillID` TINYINT(3) NOT NULL,
  `skillName` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_vietnamese_ci' NOT NULL,
  `detail` VARCHAR(200) NULL,
  PRIMARY KEY (`skillID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`student_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`student_skill` (
  `skillID` TINYINT(3) NOT NULL,
  `studentID` INT NOT NULL,
  `level` TINYINT(1) NOT NULL,
  PRIMARY KEY (`skillID`, `studentID`),
  INDEX `student_skill_fk1` (`skillID` ASC),
  INDEX `fk_student_skill_student1_idx` (`studentID` ASC),
  CONSTRAINT `student_skill_fk1`
    FOREIGN KEY (`skillID`)
    REFERENCES `internship_web`.`skill` (`skillID`),
  CONSTRAINT `fk_student_skill_student1`
    FOREIGN KEY (`studentID`)
    REFERENCES `internship_web`.`student` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_vietnamese_ci;


-- -----------------------------------------------------
-- Table `internship_web`.`student_follow_job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`student_follow_job` (
  `internship_job_jobID` INT NOT NULL,
  `student_account_userID` INT NOT NULL,
  `status` VARCHAR(10) NOT NULL DEFAULT 'waiting' COMMENT 'accepted or waiting',
  PRIMARY KEY (`internship_job_jobID`, `student_account_userID`),
  INDEX `fk_student_follow_internship_job1_idx` (`internship_job_jobID` ASC),
  INDEX `fk_student_follow_student1_idx` (`student_account_userID` ASC),
  CONSTRAINT `fk_student_follow_internship_job1`
    FOREIGN KEY (`internship_job_jobID`)
    REFERENCES `internship_web`.`internship_job` (`jobID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_follow_student1`
    FOREIGN KEY (`student_account_userID`)
    REFERENCES `internship_web`.`student` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_web`.`student_follow_partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`student_follow_partner` (
  `student_account_userID` INT NOT NULL,
  `partner_account_userID` INT NOT NULL,
  PRIMARY KEY (`student_account_userID`, `partner_account_userID`),
  INDEX `fk_student_follow_partner_partner1_idx` (`partner_account_userID` ASC),
  CONSTRAINT `fk_student_follow_partner_student1`
    FOREIGN KEY (`student_account_userID`)
    REFERENCES `internship_web`.`student` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_follow_partner_partner1`
    FOREIGN KEY (`partner_account_userID`)
    REFERENCES `internship_web`.`partner` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_web`.`lecturer_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`lecturer_student` (
  `lecturerID` INT NOT NULL,
  `studentID` INT NOT NULL,
  `plan_reportID` INT NOT NULL,
  `mark` TINYINT(1) NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`lecturerID`),
  INDEX `fk_lecturer_student_ plan_report1_idx` (`plan_reportID` ASC),
  INDEX `fk_lecturer_student_student1_idx` (`studentID` ASC),
  CONSTRAINT `fk_lecturer_student_lecturer1`
    FOREIGN KEY (`lecturerID`)
    REFERENCES `internship_web`.`lecturer` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecturer_student_ plan_report1`
    FOREIGN KEY (`plan_reportID`)
    REFERENCES `internship_web`.`plan_report` (` plan_reportID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecturer_student_student1`
    FOREIGN KEY (`studentID`)
    REFERENCES `internship_web`.`student` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_web`.`student_assession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`student_assession` (
  `studentID` INT NOT NULL,
  `assessorID` INT NOT NULL,
  `comment` VARCHAR(500) NOT NULL,
  INDEX `fk_student_rating_student1_idx` (`studentID` ASC),
  INDEX `fk_student_rating_account1_idx` (`assessorID` ASC),
  PRIMARY KEY (`studentID`, `assessorID`),
  CONSTRAINT `fk_student_rating_student1`
    FOREIGN KEY (`studentID`)
    REFERENCES `internship_web`.`student` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_rating_account1`
    FOREIGN KEY (`assessorID`)
    REFERENCES `internship_web`.`account` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internship_web`.`student_follow_lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `internship_web`.`student_follow_lecturer` (
  `studentID` INT NOT NULL,
  `lecturerID` INT NOT NULL,
  `status` VARCHAR(10) NOT NULL DEFAULT 'waiting',
  INDEX `fk_student_follow_lecturer_lecturer1_idx` (`lecturerID` ASC),
  PRIMARY KEY (`studentID`),
  CONSTRAINT `fk_student_follow_lecturer_lecturer1`
    FOREIGN KEY (`lecturerID`)
    REFERENCES `internship_web`.`lecturer` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_follow_lecturer_student1`
    FOREIGN KEY (`studentID`)
    REFERENCES `internship_web`.`student` (`account_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
